
# flutter_lintsの設定は削除
#include: package:flutter_lints/flutter.yaml

# lintの設定を追加
include: package:lint/strict.yaml # For production apps

linter:

  rules:
    # Util classes are awesome!
    # avoid_classes_with_only_static_members: false
    
    # Make constructors the first thing in every class
    # sort_constructors_first: true

    # Choose wisely, but you don't have to
    # prefer_double_quotes: true
    # prefer_single_quotes: true
